### ISSUE TITLE
Personal Records (PR) Tracking (front-end)

### ISSUE THREAD

**Issue by peterdeanwilson** [dumple123/Gym-Application#13]
- [ ] Create PR tracking component
- [ ] Display list of all-time PRs
- [ ] Implement notification or badge for new PRs
