### ISSUE TITLE
Personal Records (PR) Tracking

### ISSUE THREAD

**Issue by peterdeanwilson** [dumple123/Gym-Application#6]
- [ ] Create personal records model and migration with Prisma
- [ ] Implement API to automatically detect and store new PRs (heaviest weight lifted per exercise)
- [ ] Implement API to retrieve all-time PRs (for each exercise)
